//
//  HistorySource.swift
//  weatherProject
//
//  Created by Ege on 17.12.2019.
//  Copyright © 2019 Ege Dincer. All rights reserved.
//

import Foundation

class HistorySource{
    var histArray:[String:String] = [:]
    
    func fillHistoryArray(){
        self.histArray = [
            "Istanbul": "First inhabitants of Istanbul are dating back to second millennia BC, they were settled on the Asian side of the city. Its first name comes from Megara king Byzas who took his colonists here in the 7th century BC to establish a colony named Byzantium, the Greek name for a city on the Bosphorus. Byzas chose this spot after consulting an oracle of Delphi who told him to settle across from the 'land of the blind'. Indeed, Byzas believed that earlier settlers must have been 'blind' for overlooking this superb location at the entrance of the Bosphorus strait, only access to the Black Sea. In the 6th century BC Persians ruled the city and than Alexander the Great took it over after 4th century BC, which was a peaceful period until the 2nd century BC.In 193 AD Roman emperor Septimus Severus conquered the city and it remained under the Roman rule until 4th century AD, when emperor Constantine the Great made Byzantium the capital of entire Roman Empire and gave it his name: Constantinople, and Eastern Roman Empire was called Byzantine Empire after 5th century. The city was built on seven hills, like Rome. Early Byzantine emperors filled their city with the treasures of the ancient world, especially between 4th and 6th centuries with a population exceeded half a million. In 532 during the reign of Justinian I, riots destroyed the city. But it was rebuilt and outstanding structures such as Hagia Sophia stand as monuments to the golden age of Byzantines. Istanbul's latter history is full intrigues and sieges, it was besieged by the Arabs in the 7th and 8th centuries and by the Barbarians in the 9th and 10th, but ruled by the Fourth Crusade between 1204-1261 who destroyed and sacked all the wealth. After this, Constantinople did not regain its former richness nor strength. Ottoman Turks lead by Sultan Mehmet II conquered Constantinople in 1453. Renamed Islambol, the city became the capital of the Ottoman Empire. Between 15th and 16th centuries, sultans built many mosques and public buildings, topping the population again around half million by the mid 1500's, Istanbul was a major cultural, political, and commercial center. The name 'Istanbul' was derived from a combination of 'Islambol' ('city of Islam' in Turkish) and 'eis tin Polin' ('to the City' in Greek) throughout the centuries. Ottoman rule lasted until World War I when Istanbul was occupied by the allied troops. After years of struggle led by Ataturk against the occupying forces, the Republic of Turkey was born in 1923 and the capital was moved to Ankara province. But Istanbul has continued to expand dramatically; today its population is over 13 million and still increases constantly. It continues to be the commercial and cultural center of Turkey.",
            "Paris": "The city of Paris began in the 3rd century BC when a Celtic tribe called the Parisii built a fortified settlement on the Ile de la Cite. The Romans conquered the Parisii in 52 AD and they built a town on the River Seine. The Romans called Paris Lutetia. However Roman Paris was not a particularly large or important town. It had a population of not more than 10,000. In the late 3rd century Paris and the surrounding region were converted to Christianity. However by then the Roman Empire was in decline. In 486 a race called the Franks captured Paris. Under the Franks Paris flourished. In 845 the Vikings raided Paris. The French king paid them 7,000 pounds of silver to leave. But from the 11th century onward Paris prospered again. In the Middle Ages Paris grew rapidly and it became one of the largest towns in Europe. Its population probably reached 200,000 (that might seem small to us but it was huge by Medieval standards). King Philippe-Auguste (1180-1223) built a wall around Paris. He also built the Louvre fortress. Medieval Paris was also a busy inland port with goods being brought to and from its wharves along the Seine. Paris was also noted for its scholars. Paris University became famous. Meanwhile from the late 12th century onward the most famous cathedral in Paris, the Cathedral de Notre Dame was built. However in 1338 the Hundred Years War between France and England began and in 1348 Paris was devastated by the Black Death. In 1357 the mayor of Paris Etienne Marcel led a rebellion in Paris to try and gain more rights for Parisian merchants. However Royalist forces captured Paris in 1358 and Marcel and his followers were executed. In 1420 the English captured Paris. However the French recaptured the town in 1436.",
            "Amsterdam": "The city of Amsterdam began as a village on the River Amstel. However, in the Middle Ages, it grew rapidly as a center of trade. In 1275 Floris V, Count of Holland gave the people of 'Amstelledamme' to transport their goods by water through his territory. In 1306 the bishop of Utrecht gave Amsterdam certain rights and the little town grew rapidly. In 1323 Amsterdam was made a port for Hamburg beer. Herring curing was invented in 1385. It meant the fish lasted longer and so the herring trade from Amsterdam boomed.However Amsterdam suffered a severe fire in 1421. Another disastrous fire took place in 1452. Fire was a constant hazard when buildings were made of wood but after the second firewood was banned as a building material. The Schreierstoren tower was built in 1480. The Waag gatehouse was built in 1488.In the 16th century Amsterdam continued its growth. Meanwhile, the Protestant Reformation swept across the Netherlands despite persecution. In the 17th century, Amsterdam boomed and three great canals were built around the city. Many immigrants came to Amsterdam and its population rose to 200,000. The rise in the population of Amsterdam happened despite outbreaks of plague, which killed many people. The last outbreak was in 1663. Meanwhile, the Athenaeum Illustre opened in 1632. it became Amsterdam University in 1977. In the 18th century Amsterdam continued to be wealthy and it was also known for its tolerance. However in the early 19th century Amsterdam stagnated although a railway was built to Haarlem in 1839. In the late 19th century Amsterdam began to revive. The Industrial Revolution began to transform the city. At first industrialisation caused many social problems and in 1886 26 people were killed in the Palingoproer Riots.On the other hand new public buildings were erected. The Rijksmuseum opened in 1885 and Centraal Station was built in 1889. The Stedelijk Museum opened in 1895. Rembrandt House Museum opened in 1911.",
            "Vienna" : " Vienna was probably an important trading post for the Celts when the Romans arrived around 15 BC. They set up camp and named it Vindobona, after the Celtic tribe Vinid. The settlement blossomed into a town by the 3rd and 4th centuries, and vineyards were introduced to the surrounding area. In 881 the town, then known as ‘Wenia’, surfaced in official documents and over the ensuing centuries control of Vienna changed hands a number of times, before the Babenburgs gained the upper hand. The Habsburgs inherited it, but none of them resided here permanently until Ferdinand I in 1533; the city was besieged by Turks in 1529. Vienna was a hotbed of revolt and religious bickering during the Reformation and Counter-Reformation and suffered terribly through plague and siege at the end of the 17th century. However, the beginning of the 18th century heralded a golden age for Vienna, with baroque architecture, civil ­reform and a classical music revolution. Things turned sour at the beginning of the 19th century – Napoleon occupied the city twice, in 1805 and 1809. His reign over Europe was brief, and in 1814–15 Vienna hosted the Congress of Vienna in celebration. Vienna grew in post-Napoleon Europe and in 1873 hosted its second international event, the World Fair. The advent of WWI stalled the city’s architectural and cultural development and, by the end of the war, the monarchy had been consigned to the past. The 1920s saw the rise of fascism, and by 1934 civil war broke out in the city streets. The socialists were defeated and Vienna’s city council dissolved. Austria was ripe for the picking, and Hitler came a-harvesting; on 15 March 1938 he entered the city to the cries of 200, 000 ecstatic Viennese. Vienna suffered heavily under Allied bombing, and on 11 April 1945 advancing Russian troops liberated the city. The Allies joined them until Vienna became independent in 1955, and since then it has gone from the razor’s edge of Cold War to the focal point between new and old EU member nations.",
            "London": "It is thought that London in prehistoric times was merely a collection of scattered rural settlements. Spear heads and weapons from the Bronze and Iron Ages have been found around the Thames, and a recent archaeological dig near Vauxhall discovered evidence of a possible wooden bridge across the Thames around 3,000 years ago! It was the Romans who were responsible for the city we know today as London. They invaded Britain in AD43, and soon afterwards founded the city of Londinium. It is thought that the original city was small - about the size of Hyde Park! In AD60 Queen Boudica (also known as Boadicia) of the Iceni tribe rose up against the Romans, who fled. The city was burned to the ground. However, the Romans eventually regained control and rebuilt London, this time adding a Forum (market) and Basilica (a business centre), and slowly building a wall around the city to protect it from further invasion.",
            "Berlin": "The great city of Berlin began in the 13th century. Originally there were 2 settlements on either side of the Spree River, Colln and Berlin. Colln was first mentioned in 1237 while Berlin was first mentioned in 1244. The two towns grew rapidly and in 1307 they made an alliance. In 1360 Berlin-Colln became a member of the Hanseatic League. By the 15th century they were flourishing towns with about 8,000 inhabitants. In 1432 Berlin and Colln were formally united. It would seem small to us but by Medieval standards it was a large and prosperous town. In the early 16th century the Reformation reached Brandenburg (the state that contained Berlin). The elector of Brandenburg became a Protestant in 1539. Berlin continued to prosper. However like all towns in the 16th century Berlin suffered from outbreaks from the plague. The plague struck Berlin in 1576, 1598 and 1699. Worse, like the rest of Germany was devastated by the Thirty Years War 1618-1648. Its population dropped to around 6,000. However Berlin recovered and in the late 17th century it flourished once again. Its population rose rapidly helped by French Protestants fleeing religious persecution. By the early 18th century the population of Berlin was over 50,000. In 1701 Elector Friedrich III became King Friedrich I of Prussia. Frederick the Great reigned from 1740 to 1786. Under him Berlin prospered and much great architecture was built. "
        ]
    }
    
    func getCityHistory(city:String) -> String{
        return histArray[city]!
    }
}
